name: Orlando Malice
favicon: null
layout_spectrum: 0.17445772769860923
typography_spectrum: 0.5344422000925988
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9847375145182014
  lightness: 0.7559422147460282
  saturation: 0.7910247182007879
  rhythmicContrast: 0.21968463668599725
purpose: []
