name: Orlando Malice
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88862
title: XIX PROJECT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c23235'
    - '#040205'
    - '#451517'
    - '#8a2729'
    - '#800000'
  brandStrength: 0.875
  lightness: 0.7559422147460282
  saturation: 0.7910247182007879
  rhythmicContrast: 0.21968463668599725
purpose: []
